print('Naam Invoer')
name = input('Geef uw naam ')
print('Hallo ' + name)
print('Adres Invoer')
adres = input('Wat is uw adres? ')
print('Postcode Invoer')
postcode = input('Wat is uw postcode? ')
print('Woonplaats Invoer')
woonplaats = input('Wat is uw woonplaats? ')

print('  ---------------------------------------------------- ')
print(' |  Naam      : ' + str(name) + '                      ')
print(' |  Adres     : ' + str(adres) + '                     ')
print(' |  Postcode  : ' + str(postcode) + '                  ')
print(' |  Woonplaats: ' + str(woonplaats) + '                ')   
print('  ---------------------------------------------------- ')